import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import FadeIn from "@/components/FadeIn";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Veeral Narang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.variable} antialiased `}>
        <Navbar />
        <div className="flex flex-col min-h-screen ">
          <FadeIn>
            <main className="main-container  flex-1 ">{children}</main>
          </FadeIn>
        </div>
      </body>
    </html>
  );
}
